config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :todos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo = Todo.all
  end

  def create
    @todo = Todo.new(params.require(:todo).permit(:title))

    if @todo.save
      redirect_to @todo
    else
      render 'new'
    end
  end

  def new
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(params.require(:todo).permit(:title))
      redirect_to @todo
    else
      render 'edit'
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to todos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoruby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Find your todoruby</h1>
<p>Lorem ipsum dolor sit amet</p>
<%= link_to 'Check your to-dos', todos_path %>

app/views/todos/_form.html.erb
<%= form_with scope: :todo, url: todos_path,local: true do |form| %>
  <% if @todo.errors.any? %>
    <h2><% pluralize(@todo.errors.count, "error") %></h2> prohibited this article from being saved:
    <ul>
      <% @todo.errors.full_message.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= form.label :title %> <br/>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<%= link_to 'New To-Do', new_todo_path %>
<hr/>
<table>
  <tr>
    <td>Title</td>
  </tr>
  <% @todo.each do |todo| %>
    <tr>
      <td><%= todo.title %></td>
      <td><%= link_to 'Show', todo_path(todo) %></td>
      <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
      <td><%= link_to 'Delete', todo_path(todo),
              method: :delete,
              data: { confirm: 'Are you sure' } %></td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<h1>Add a To-Do</h1>

<%= render 'form' %>

<%= link_to 'Back', @todo %>

app/views/todos/show.html.erb
ID: <%= @todo.id %><br/>
Title: <%= @todo.title %><br/>
<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>